### ISSUE TITLE
reproduce result of office-home

### ISSUE THREAD

**Issue by tjtmddnjswkd** [Jhyun17/CoWA-JMDS#2]
Thanks to the author for contributing the code!

I’m trying to train a model on office-home, but there is only a script for reproducing the visda results. 
So I have difficulty to get the office-home results.

Could you provide a script to reproduce the results for office-home?

**Comment by Jhyun17** [comment]
I add a script for office-home dataset in my main page.

If you had any additional question, please do not hesitate.

Thanks.

**Comment by tjtmddnjswkd** [comment]
Thanks for the reply!

Thanks to the script you provided, I was able to reproduce it successfully.

Additionally, can I get the code to reproduce the oda results?

**Comment by Jhyun17** [comment]
Oh, I apologize for the late reply. 

I recognized your request yesterday. 

Please refer to the attached file and try to reproduce it.

Thanks.
[oda_codes.zip](https://github.com/Jhyun17/CoWA-JMDS/files/10937499/oda_codes.zip)
